### PR TITLE
Add necessary permissions for release action

### LINKED ISSUE #240: [Bug]: Job permissions for release workflow
### Severity

Medium

### What release version, tag or commit-hash did you use?

https://github.com/eclipse-velocitas/vehicle-app-python-template/commit/b6d9595b51157eeb3e7c3c0a8d3b4600c9519b93

### Current Behavior

In the [quick start](https://eclipse.dev/velocitas/docs/tutorials/quickstart/quickstart/#how-to-release-your-_vehicle-app_) referenced from the [README](https://github.com/eclipse-velocitas/vehicle-app-python-template/blob/main/README.md) it is described how to create a release by running the [release](https://github.com/eclipse-velocitas/vehicle-app-python-template/blob/main/.github/workflows/release.yml) workflow.

It does not state anything about that you might need to change job rights. When running release after using the template errors were reported:

image

### Steps to Reproduce

As above

### Expected Behavior

No error

### Possible Solution

It appears that my GITHUB_TOKEN for the created repo does not have write rights.
After adding rights like below the job could be run successfully.

I see two possible improvements:

- Either add the lines below to https://github.com/eclipse-velocitas/vehicle-app-python-template/blob/main/.github/workflows/release.yml
- Or describe in documentation that you may need to change your permissions for GITHUB_TOKEN

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

```
# Needed if GITHUB_TOKEN by default do not have right to create release
permissions:
  contents: write
  packages: write
```

### Additional Information

_No response_

### Code of Conduct

- [X] I agree to follow this project's "Code of Conduct".

### LINKED ISSUE #242: [Bug]: Release workflow is not working for an unmodifidy template clone
### Severity

Trivial

### What release version, tag or commit-hash did you use?

v0.1.2

### Current Behavior

Github action steps are failed
- Upload image (SampleApp) 
- [Generate release documentation](https://github.com/arsibo/mynew_app/actions/runs/9095832370/job/24999911401#step:15:12)
- gen-desired-state / Generate desired state for SampleApp 

### Steps to Reproduce

1. Clone created MyOrg/MyFirstVehicleApp repository locally using your favorite Git tool
2.  Open the Code page of your repository on GitHub
3. Click on Create a new release in the Releases section on the right side
4. Enter a version (e.g. v1.0.0) and click on Publish release
    

### Expected Behavior

- Push container image to ghcr.io 

### Possible Solution

_No response_

### Additional Information

The idea was to demonstrate how easy it is to get an app container.
APP function is not required for this.

### Code of Conduct

- [X] I agree to follow this project's "Code of Conduct".

### PR DESCRIPTION
**Pull request by erikbosch**
A Github default token does not not have content/package permission

.velocitas.json updated manually
The others updated automatically by

- velocitas init
- velocitas sync

Notice taken from build

Fixes #240
Fixes #242

Tested in https://github.com/erikbosch/vehicle-example-app2/actions/workflows/release.yml

### CODE REVIEW

**Comment by erikbosch** [comment]
I actually do not know why https://github.com/eclipse-velocitas/vehicle-app-python-template/blob/main/.github/workflows/ensure-lifecycle.yml fails, or what it even intends to check.

Any ideas @BjoernAtBosch  @MP91 @doosuu

**Comment by MP91** [comment]
@erikbosch you need to change this here: https://github.com/eclipse-velocitas/devenv-github-workflows/blob/main/src/python-app/workflows/release.yml

than you need to create a new release of the workflow package and use that in the template

**Comment by erikbosch** [comment]
> @erikbosch you need to change this here: https://github.com/eclipse-velocitas/devenv-github-workflows/blob/main/src/python-app/workflows/release.yml
> 
> than you need to create a new release of the workflow package and use that in the template

Ah, so the check verifies that the workflow in this template repo is identical to the workflow in https://github.com/eclipse-velocitas/devenv-github-workflows/blob/main/src/python-app/workflows/release.yml. Thanks for the info.

**Comment by erikbosch** [comment]
This one should be ready for review now @MP91 @dennismeister93 @BjoernAtBosch

**Review by dennismeister93 — APPROVED** [review]
lgtm

**Pull request merged**
