### PR TITLE
fix: adjust the dapr --runtime-version 1.8.1

### PR DESCRIPTION
**Pull request by emsameen**
# Description

Pin the dap cli and runtime versions for the stable 1.8.0/1.8.1 release.

## Azure DevOps PBI/Task reference

AB#10569

## Checklist

* [x] Vehicle App can be started with dapr run and is connecting to vehicle data broker
* [x] Vehicle App can process MQTT messages and call the seat service
* [x] Vehicle App can be deployed to local K3D and is running
* [ ] Created/updated tests, if necessary. Code Coverage percentage on new code shall be >= 70%.
* [ ] Extended the documentation in Velocitas repo
* [ ] Extended the documentation in README.md

* [x] Devcontainer can be opened successfully
* [ ] Devcontainer can be opened successfully behind a corporate proxy
* [x] Devcontainer can be re-built successfully

* [ ] Release workflow is passing

### CODE REVIEW

**Review by DocMoebiuz — CHANGES_REQUESTED** [review]
improvements:
* prequisites json can have proper json nesting and keep version-label for cli and runtime
* simplify test in line 29
* treat install of cli and runtime independently, refactor if else branches

**Comment by emsameen** [comment]
> 

Done as discussed

**Comment by emsameen** [comment]
> improvements:
> 
> * prequisites json can have proper json nesting and keep version-label for cli and runtime
> * simplify test in line 29
> * treat install of cli and runtime independently, refactor if else branches

Done as discussed!

**Review by DocMoebiuz — APPROVED** [review]
Great!

**Pull request merged**
