### PR TITLE
Update packages and sync new files

### PR DESCRIPTION
**Pull request by dennismeister93**
This PR updates packages and sync new files

### CODE REVIEW

**Comment by dennismeister93** [comment]
"Ensure lifecycle management" fails because there are changes in it's file and these changes are not on main yet

**Comment by MP91** [comment]
> "Ensure lifecycle management" fails because there are changes in it's file and these changes are not on main yet

why is this checking main? shouldn't it check the state of the PR?

**Comment by dennismeister93** [comment]
Problem is that news devcontainer-setup needs atleast cli version 0.11.0..
Triggered update of CLI in base image:
https://github.com/eclipse-velocitas/devcontainer-base-images/pull/74

**Review by doosuu — APPROVED** [review]
lgtm

**Review by doosuu — APPROVED** [review]
lgtm

**Pull request merged**
